project:
  type: website

website:
  title: "MridsBlogOfAwesomeness"
  google-analytics: G-PKNCJ36Q1P
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mrisrijgd1
      - icon: twitter
        href: https://twitter.com/Mridul17977912
      - icon: linkedin
        href: https://www.linkedin.com/
format:
  html:
    theme: solar
    css: styles.css



